apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    argocd.happening.dev/domain: ops
    argocd.happening.dev/environment: dev
    argocd.happening.dev/layer: two
spec:
  project: default

  destination:
    namespace: loki

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  source:
    repoURL: https://github.com/IgorAssuncao/loki-test
    path: loki/chart
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
