apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: loki
spec:
  project: default

  destination:
    namespace: loki
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  source:
    repoURL: https://github.com/IgorAssuncao/loki-test
    path: loki/chart
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
